### ISSUE TITLE
Legacy Version Installation doesnt work

### ISSUE THREAD

**Issue by RyuguDev** [GAME-CLI-SRV-DEV/ViaVersionProtocolSupport#15]
"you need spigot 1.4.4-1.6.4
Download VVPS-Spigot, Put it in the plugins folder
and restart your server."

My Server:

04:44:48 [INFORMATION] This server is running CraftBukkit version git-Spigot-1.5.2-R1.0-61-gfb828bb (MC: 1.5.2) (Implementing API version 1.5.2-R1.1-SNAPSHOT)
04:44:49 [SCHWERWIEGEND] Could not load 'plugins/ViaLegacy.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: ViaVersion
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
	at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
	at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:219)
	at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
	at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
	at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
	at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
	at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

ViaVersion doesnt Support 1.5.2 so?

**Comment by Outfit8TSB** [comment]
vialegacy.jar addon Only Exists To Make This Plugin Work. Legacy Version is not yet supported due to ViaVersion not working on 1.5. 

Sorry. 😥




네이버 메일 앱에서 보냈습니다.

-----Original Message-----
보낸사람: "Ryūgū Rena (竜宮 レナ)" ***@***.***>
받는사람: "GAME-CLI-SRV-DEV/ViaVersionProtocolSupport" ***@***.***>
참조: "Subscribed" ***@***.***>
날짜:2024.12.19 오후 06:47:55 (GMT+09:00)
제목: [GAME-CLI-SRV-DEV/ViaVersionProtocolSupport] Legacy Version Installation doesnt work (Issue #15)

"you need spigot 1.4.4-1.6.4
Download VVPS-Spigot, Put it in the plugins folder
and restart your server."
My Server:
04:44:48 [INFORMATION] This server is running CraftBukkit version git-Spigot-1.5.2-R1.0-61-gfb828bb (MC: 1.5.2) (Implementing API version 1.5.2-R1.1-SNAPSHOT)
04:44:49 [SCHWERWIEGEND] Could not load 'plugins/ViaLegacy.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: ViaVersion
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:195)
at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:241)
at org.bukkit.craftbukkit.v1_5_R3.CraftServer.(CraftServer.java:219)
at net.minecraft.server.v1_5_R3.PlayerList.(PlayerList.java:55)
at net.minecraft.server.v1_5_R3.DedicatedPlayerList.(SourceFile:11)
at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:93)
at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
ViaVersion doesnt Support 1.5.2 so?

**Comment by Outfit8TSB** [comment]
I Use Naver Mail. Ignore the korean characthers.

Let Me Tell You with Simple one.
ViaLegacy Requires ViaVersion To Function.

For Useful Information,
Please Go to ViaVersion Discord.
