### ISSUE TITLE
[BUG]: ViaProxy Is Not Starting up

### ISSUE THREAD

**Issue by Outfit8TSB** [GAME-CLI-SRV-DEV/ViaVersionProtocolSupport#22]
### What happened?

ViaVersionProtocolSupport has registered the Platform, but it's Not Starting On ViaProxy. This will be announced when i register the plugin to ViaProxy Wiki.

### Version

8.55-1.21.1-5.0.0 (ProtocolSupport Version 8.55, For 1.21.1 Minecraft, Requires ViaVersion 5.0.0)

### What Platform are you seeing the problem on?

ViaProxy

### Relevant log output

```shell
[15:00:21] [main/ERROR] (ViaProxy) Failed to enable plugin 'ViaVersionProtocolSupport-ViaProxy'
 java.lang.IllegalArgumentException: ViaVersion has not loaded the platform yet
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[ViaProxy-3.3.7.jar:?]
        at com.viaversion.viaversion.api.Via.manager(Via.java:84) ~[ViaProxy-3.3.7.jar:?]
        at com.viaversion.viaversion.api.Via.getManager(Via.java:50) ~[ViaProxy-3.3.7.jar:?]
        at me.falixsrv.approximasteranarchy2004.ViaVersionProtocolSupport.viaproxy.ViaProxyBootstrap.onEnable(ViaProxyBootstrap.java:19) ~[?:?]
        at net.raphimc.viaproxy.plugins.ViaProxyPlugin.enable(ViaProxyPlugin.java:38) ~[ViaProxy-3.3.7.jar:?]
        at net.raphimc.viaproxy.plugins.PluginManager.enablePlugin(PluginManager.java:160) [ViaProxy-3.3.7.jar:?]
        at net.raphimc.viaproxy.plugins.PluginManager.loadPlugins(PluginManager.java:91) [ViaProxy-3.3.7.jar:?]
        at net.raphimc.viaproxy.plugins.PluginManager.<init>(PluginManager.java:52) [ViaProxy-3.3.7.jar:?]
        at net.raphimc.viaproxy.ViaProxy.injectedMain(ViaProxy.java:200) [ViaProxy-3.3.7.jar:?]
        at net.raphimc.viaproxy.ViaProxy.main(ViaProxy.java:100) [ViaProxy-3.3.7.jar:?]
```

### Code of Conduct

- [X] I agree.

**Comment by Outfit8TSB** [comment]
### What happened?

ViaVersionProtocolSupport is Not Working!
platform:viaproxy

[latest.log](https://github.com/user-attachments/files/28226379/latest.log)

### Version

8.55-1.21.1-5.0.0 (ProtocolSupport Version 8.55, For 1.21.1 Minecraft, Requires ViaVersion 5.0.0)

### What Platform are you seeing the problem on?

ViaProxy

### Relevant log output

```shell
[15:41:41] [main/INFO] (ViaProxy) Initializing ViaProxy GUI v3.4.9 (git-ViaProxy-3.4.9:82f64be) (Injected using Launcher Agent)...
[15:41:41] [main/INFO] (ViaProxy) Using java version: OpenJDK 64-Bit Server VM 21.0.10 (Ubuntu) on Linux
[15:41:41] [main/INFO] (ViaProxy) Available memory (bytes): 3646947328
[15:41:41] [main/INFO] (ViaProxy) Working directory: /home/mrblizzard/Desktop/viaproxy
[15:41:42] [main/INFO] (ViaProxy) Loaded plugin 'ViaVersionProtocolSupport-ViaProxy' by Approximaster Studios 2004 (v8.55-3.3.6-5.2.1)
[15:41:42] [main/INFO] (LoggerPrintStream) [STDOUT]: Loading...
[15:41:42] [main/ERROR] (ViaProxy) Failed to enable plugin 'ViaVersionProtocolSupport-ViaProxy'
java.lang.IllegalArgumentException: ViaVersion has not loaded the platform yet
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
	at com.viaversion.viaversion.api.Via.manager(Via.java:84)
	at com.viaversion.viaversion.api.Via.getManager(Via.java:50)
	at me.falixsrv.approximasteranarchy2004.ViaVersionProtocolSupport.viaproxy.ViaProxyBootstrap.onEnable(ViaProxyBootstrap.java:19)
	at net.raphimc.viaproxy.plugins.ViaProxyPlugin.enable(ViaProxyPlugin.java:38)
	at net.raphimc.viaproxy.plugins.PluginManager.enablePlugin(PluginManager.java:160)
	at net.raphimc.viaproxy.plugins.PluginManager.loadPlugins(PluginManager.java:91)
	at net.raphimc.viaproxy.plugins.PluginManager.<init>(PluginManager.java:52)
	at net.raphimc.viaproxy.ViaProxy.injectedMain(ViaProxy.java:217)
	at net.raphimc.viaproxy.ViaProxy.main(ViaProxy.java:102)
[15:41:42] [main/INFO] (LoggerPrintStream) [STDERR]: [ERROR] Failed to migrate old ViaLoader configs
[15:41:42] [main/INFO] (LoggerPrintStream) [STDERR]: org.apache.commons.io.FileExistsException: File element in parameter 'destFile' already exists: '/home/mrblizzard/Desktop/viaproxy/viaaprilfools.yml'
[15:41:42] [main/INFO] (LoggerPrintStream) [STDERR]: 	at org.apache.commons.io.FileUtils.requireAbsent(FileUtils.java:2857)
[15:41:42] [main/INFO] (LoggerPrintStream) [STDERR]: 	at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2571)
[15:41:42] [main/INFO] (LoggerPrintStream) [STDERR]: 	at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2549)
[15:41:42] [main/INFO] (LoggerPrintStream) [STDERR]: 	at org.apache.commons.io.FileUtils.moveFileToDirectory(FileUtils.java:2609)
[15:41:42] [main/INFO] (LoggerPrintStream) [STDERR]: 	at org.apache.commons.io.FileUtils.moveToDirectory(FileUtils.java:2637)
[15:41:42] [main/INFO] (LoggerPrintStream) [STDERR]: 	at net.raphimc.viaproxy.protocoltranslator.ProtocolTranslator.moveConfigs(ProtocolTranslator.java:88)
[15:41:42] [main/INFO] (LoggerPrintStream) [STDERR]: 	at net.raphimc.viaproxy.protocoltranslator.ProtocolTranslator.init(ProtocolTranslator.java:68)
[15:41:42] [main/INFO] (LoggerPrintStream) [STDERR]: 	at net.raphimc.viaproxy.ViaProxy.injectedMain(ViaProxy.java:219)
[15:41:42] [main/INFO] (LoggerPrintStream) [STDERR]: 	at net.raphimc.viaproxy.ViaProxy.main(ViaProxy.java:102)
[15:41:42] [Via-Mappingloader-1/INFO] (ViaVersion) Loading block connection mappings ...
[15:41:43] [main/INFO] (ViaBackwards) Loading translations...
[15:41:43] [main/INFO] (ViaBackwards) Registering protocols...
[15:41:43] [main/INFO] (ViaRewind) Registering protocols...
[15:41:44] [main/INFO] (ViaBedrock) Started resource pack HTTP server on http://127.0.0.1:35389/
[15:41:44] [main/INFO] (ViaVersion) ViaVersion detected lowest supported version by the proxy: 1.7.2-1.7.5 (4)
[15:41:44] [main/INFO] (ViaVersion) Highest supported version by the proxy: 1.21.11 (774)
[15:41:44] [Via Async Task 1/WARN] (ViaVersion) There is a newer plugin version available: 5.9.1, you're on: 5.7.2
[15:41:45] [main/INFO] (ViaProxy) ViaProxy started successfully!
[15:41:45] [Via Async Scheduler 0/INFO] (ViaVersion) Finished mapping loading, shutting down loader executor.
[15:41:46] [ForkJoinPool.commonPool-worker-1/WARN] (ViaProxy) You are running an outdated version of ViaProxy! Latest version: 3.4.11
```

### Code of Conduct

- [x] I agree.

Merge from #30 - MrBlizzard
