### ISSUE TITLE
[BUG]: ViaVersionProtocolSupport Wont Start at all!

### ISSUE THREAD

**Issue by Outfit8TSB** [GAME-CLI-SRV-DEV/ViaVersionProtocolSupport#23]
### What happened?

ViaVersionProtocolSupport is Not Starting Due to an error.

### Version

8.55-1.21.1-5.0.0 (ProtocolSupport Version 8.55, For 1.21.1 Minecraft, Requires ViaVersion 5.0.0)

### What Platform are you seeing the problem on?

Bukkit

### Relevant log output

```shell
[20:56:15 ERROR]: Error occurred while enabling VVPS-Bukkit v8.55-1.21.1-5.0.0 (Is it up to date?)
java.lang.IllegalArgumentException: Packet LOGIN in class me.falixsrv.approximasteranarchy2004.ViaVersionProtocolSupport.protocol.r1_7_2_5tor1_6_4.Protocolr1_7_2_5tor1_6_4 has no mapping - it needs to be manually cancelled or remapped
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:165) ~[guava-32.1.2-jre.jar:?]
        at ViaVersion-5.2.0.jar/com.viaversion.viaversion.api.protocol.AbstractProtocol.registerPacketIdChanges(AbstractProtocol.java:188) ~[ViaVersion-5.2.0.jar:?]
        at ViaVersion-5.2.0.jar/com.viaversion.viaversion.api.protocol.AbstractProtocol.initialize(AbstractProtocol.java:121) ~[ViaVersion-5.2.0.jar:?]
        at ViaVersion-5.2.0.jar/com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:209) ~[ViaVersion-5.2.0.jar:?]
        at ViaVersion-5.2.0.jar/com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:203) ~[ViaVersion-5.2.0.jar:?]
        at ViaVersionProtocolSupport-PaperSpigotMCPlugin.jar/me.falixsrv.approximasteranarchy2004.ViaVersionProtocolSupport.api.VVPSPlatform.init(VVPSPlatform.java:50) ~[ViaVersionProtocolSupport-PaperSpigotMCPlugin.jar:?]
        at ViaVersionProtocolSupport-PaperSpigotMCPlugin.jar/me.falixsrv.approximasteranarchy2004.ViaVersionProtocolSupport.ViaVersionProtocolSupportBukkit.init(ViaVersionProtocolSupportBukkit.java:80) ~[ViaVersionProtocolSupport-PaperSpigotMCPlugin.jar:?]
        at ViaVersionProtocolSupport-PaperSpigotMCPlugin.jar/me.falixsrv.approximasteranarchy2004.ViaVersionProtocolSupport.ViaVersionProtocolSupportBukkit.onEnable(ViaVersionProtocolSupportBukkit.java:74) ~[ViaVersionProtocolSupport-PaperSpigotMCPlugin.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Code of Conduct

- [X] I agree.

**Comment by Outfit8TSB** [comment]
ughhh... how did myles do that...
